version: '3.8'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=db_halloween_pw
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=halloween
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: db_halloween_pw
      MYSQL_DATABASE: halloween
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    image: frontend
    build:
      context: ../halloween-front-end
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: